import type { Metadata } from "next"
import "./globals.css"

import { Amplify } from "aws-amplify"
// import outputs from "./../../amplify_outputs.json"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

// Amplify.configure(outputs)

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    )
}
